# Generated by Django 5.0.3 on 2024-04-25 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Camera', max_length=50)),
                ('status', models.CharField(choices=[('ON', 'On'), ('OFF', 'Off'), ('DIS', 'Disconnected')], default='OFF', max_length=3)),
                ('type', models.CharField(choices=[('AREA', 'Area camera'), ('ENTR', 'Entrance camera')], default='AREA', max_length=4)),
                ('video_ip', models.CharField(max_length=50)),
                ('camera_ip', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTotal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('people_in', models.PositiveBigIntegerField()),
                ('people_out', models.PositiveBigIntegerField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.camera')),
            ],
            options={
                'ordering': ['-date', 'camera'],
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hour', models.IntegerField()),
                ('date', models.DateField()),
                ('people_in', models.PositiveBigIntegerField()),
                ('people_out', models.PositiveBigIntegerField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.camera')),
            ],
            options={
                'ordering': ['-hour', '-date', 'camera'],
            },
        ),
    ]
