# Generated by Django 5.0.3 on 2024-05-04 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestMetadata',
            fields=[
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.camera')),
                ('people_in', models.PositiveBigIntegerField()),
                ('people_out', models.PositiveBigIntegerField()),
            ],
        ),
    ]
