# Generated by Django 5.0.3 on 2024-03-28 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ON', 'On'), ('OFF', 'Off'), ('DIS', 'Disconnected')], default='OFF', max_length=3)),
                ('ip', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('people_in', models.PositiveBigIntegerField()),
                ('people_out', models.PositiveBigIntegerField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.camera')),
            ],
            options={
                'ordering': ['camera', '-time'],
                'indexes': [models.Index(fields=['camera', '-time'], name='report_meta_camera__4f8e85_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='metadata',
            constraint=models.UniqueConstraint(fields=('camera', 'time'), name='unique-camera-time'),
        ),
    ]
