# Generated by Django 5.0.3 on 2024-03-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='name',
            field=models.CharField(default='Camera <django.db.models.fields.AutoField>', max_length=50),
        ),
    ]
